#storage = "vec"
N = false
arc = true
bip = false
contiguous = false
padded = true
pow2 = false

# TODO: docstring? RingBuffer, module?
#rb_doc = """
#    /// Ring buffer ...
#    ///
#    /// TODO: ...
#"""
